### ISSUE TITLE
Java 7 compatibility

### ISSUE THREAD

**Issue by henryaka** [jameskleeh/groovy-excel-builder#12]
Hello I have a problem with the library it does not compile with my version of grails.
I use
Java 1.7 .0_79, Grails 2.2.4, Groovy 2.4.8,
I have the following error
[FAILED] com.jameskleeh # excel-builder; 0.4.0! Excel-builder.zip:

**Comment by jameskleeh** [comment]
I haven't tested it with Java 7. If you'd like you can clone it and test with Java 7. If the changes are minimal, I'd be glad to publish a version that is compatible.

**Comment by jameskleeh** [comment]
@henryaka Can you try with `0.4.1.BUILD-SNAPSHOT` ? That build was published with JDK7

**Comment by henryaka** [comment]
ok i try it

**Comment by jameskleeh** [comment]
@henryaka Any luck?

**Comment by henryaka** [comment]
@jameskleeh no nothing
