### ISSUE TITLE
Horizontal alignment bug

### ISSUE THREAD

**Issue by tobia** [jameskleeh/groovy-excel-builder#14]
This:

	sheet(width: 20) {
		row {
			cell("right", [alignment: HorizontalAlignment.RIGHT])
		}
		row {
			cell("left", [alignment: HorizontalAlignment.LEFT])
		}
	}

should give a cell with "right" that is right-aligned and one with "left" that is left-aligned. Instead both cells are right-aligned (at least, when opening the file in LibreOffice.)

**Comment by jameskleeh** [comment]
I'll take a look, thanks

**Comment by jameskleeh** [comment]
I can't reproduce this issue with opening the file in macOS numbers. Please verify the issue occurs in actual Excel or Numbers.
