### ISSUE TITLE
How do I set the cell width?

### ISSUE THREAD

**Issue by WonderLand33** [jameskleeh/groovy-excel-builder#15]
For example:

![image](https://user-images.githubusercontent.com/10755158/27526285-53c3246e-5a77-11e7-9aa8-ef5fd0cb3962.png)

**Comment by mfreeman-xtivia** [comment]
I too would *LOVE* to know the answer to this one....

**Comment by jameskleeh** [comment]
Can you try to call `autoSizeColumn(columnIndex, false)` on the sheet?

```
sheet { XSSFSheet sheet -> 
    //after populating all cells
    sheet.autoSizeColumn(..)
}
```

**Comment by mfreeman-xtivia** [comment]
James that works perfectly for me! Thanks
