### ISSUE TITLE
Border style on merged cells applies only to the first cell

### ISSUE THREAD

**Issue by surfing** [jameskleeh/groovy-excel-builder#16]
If you create a merge cell with border styling, the border styling only applies to first cell.
Applying the border style on row level does not work, too.
```
row {
    defaultStyle([border: BorderStyle.THIN])
    merge('Test', 1, [border: BorderStyle.THIN])
}

```
With this only the cell A1 has a border but not B1

**Comment by jameskleeh** [comment]
Fixed with version 0.4.1. This took a lot more effort than I expected due to the `RegionUtil` class not supporting custom colors
