### ISSUE TITLE
Unit-testing a cell with numeric value fails on getNumericCellValue()

### ISSUE THREAD

**Issue by brampat** [jameskleeh/groovy-excel-builder#17]
We've written an Excel-exporter using you library and it seems to work just fine. Even numeric cells appear to be in numeric. But when I write a unit-test and try to read the numeric cells using the code below, I get an IllegalStateException: "Cannot get a NUMERIC value from a STRING cell"

`sheet.getRow(1).getCell(0).getNumericCellValue() == '100'`

I've tried to explicitly set the cell-type to numeric, using the code below. This has no effect, I keep getting the exception listed above.

`                        groupRow.getValues().collect { RowValue rcells ->
                            if (rcells.value != '-' && rcells.numericValue != null) {
                                XSSFCell customCell = cell(rcells.numericValue, [format:xlNumberFormat(rcells.value)])
                                customCell.setCellType(CellType.NUMERIC)
                                customCell
                            } else {
                                cell(rcells.value)
                            }
                        }
`

Is this expected behavior?

**Comment by brampat** [comment]
Note:
When I print-out the Row. I see 
`t="s"`

Full:
`Row 1: <xml-fragment r="2" xmlns:main="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <main:c r="A2" t="s">
    <main:v>0</main:v>
  </main:c>
  <main:c r="B2" t="s">
    <main:v>1</main:v>
  </main:c>
  <main:c r="C2" t="s">
    <main:v>2</main:v>
  </main:c>
  <main:c r="D2" t="s">
    <main:v>3</main:v>
  </main:c>
  <main:c r="E2" t="s">
    <main:v>4</main:v>
  </main:c>`

Further-more, the code to write the header reads:
`                columns {
                    headerRow.collect {hcell -> column(hcell, hcell)}
                }
`
The header is perfectly visible in the Excel, but if I test on the row(0) content, it appears empty:
`Row 0: <xml-fragment r="1" xmlns:main="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <main:c r="A1"/>
  <main:c r="B1"/>
  <main:c r="C1"/>
  <main:c r="D1"/>
  <main:c r="E1"/>
  <main:c r="F1"/>
  <main:c r="G1"/>
</xml-fragment>`

**Comment by jameskleeh** [comment]
I've just added this test which passes:

```
    @Issue('https://github.com/jameskleeh/groovy-excel-builder/issues/17')
    void "test cell with number value"() {
        given:
        XSSFWorkbook workbook = ExcelBuilder.build {
            sheet {
                row {
                    cell(3)
                }
            }
        }

        when:
        Cell cell = workbook.getSheetAt(0).getRow(0).getCell(0)

        then:
        noExceptionThrown()
        cell.cellTypeEnum == CellType.NUMERIC
        cell.numericCellValue == 3D
    }
```

Did you register a renderer for the class?

**Comment by jameskleeh** [comment]
Basically the easiest way to convey the problem is to create a PR with a failing test, or upload an example project

**Comment by brampat** [comment]
Okay, solved it. My test was set up incorrect.
