### ISSUE TITLE
Exception :  Caused by: java.lang.ClassNotFoundException: org.apache.poi.common.usermodel.HyperlinkType

### ISSUE THREAD

**Issue by AITSAID** [jameskleeh/groovy-excel-builder#19]
Hi Sir , 
i'm trying to use your library , and i found alot of missing libs , i added about 4 libs , and now i'm stack with this one , 
can you please check and advice ? 
FYI , i'm running the basic example

**Comment by jameskleeh** [comment]
That class is in `org.apache.poi:poi:3.16`, which should be included transitively if you are using a dependency management system
