### ISSUE TITLE
question - setting width of each column in a sheet

### ISSUE THREAD

**Issue by vvanan** [jameskleeh/groovy-excel-builder#20]
Hi
I have 2 columns in a spread sheet. In that I need to set first column width as 15 and second column width as 25.
So I started writing a sheet as 

Sheet ("sheet1") {
   column { [width: 15]
           cell('row1col1')
           cell('row2col1')
    }
  column { [width: 25]
           cell('row1col2')
           cell('row2col2')
    }
}

But my width of the columns are not changed in the output. I tried defaultStyle method also.
Can you please help in this.

**Comment by vvanan** [comment]
Hi,
For the above question I used underlying api. and its working for me. 
Sheet ("sheet1") { **XSSFSheet sheet->
sheet.setColumnWidth(0, 5000)
sheet.setColumnWidth(1, 7000)**
column { 
cell('row1col1')
cell('row2col1')
}
column { 
cell('row1col2')
cell('row2col2')
}
}

**Is this is the only way or any other way in our library?**

**Comment by jameskleeh** [comment]
@vvanan Doesn't seem to be a way to do this via the library, however I think there should be. I'll work on getting this feature added

**Comment by jameskleeh** [comment]
Feature was added in 0.4.2

**Comment by vvanan** [comment]
Thanks. Its working fine.
