### ISSUE TITLE
Consider using SXSSF

### ISSUE THREAD

**Issue by tobia** [jameskleeh/groovy-excel-builder#21]
SXSSF (Streaming XSSF) is the API variant that avoids storing the entire workbook in the Java heap memory as it's being built. This is important for most data extraction usages, in the same way as Groovy supports the `Sql#eachRow()` method as a streaming, memory-conserving option over `Sql#rows()`.

I would suggest considering whether to use SXSSF by default, or at least toggled by an option.

See the HOWTO here http://poi.apache.org/spreadsheet/how-to.html#sxssf and various topics such as https://stackoverflow.com/questions/47851078/

**Comment by jameskleeh** [comment]
@tobia I wasn't aware this was an option. Thanks for bringing it to my attention. I'll look into it

**Comment by jameskleeh** [comment]
Done in 1.0.0 snapshot - please test
