### ISSUE TITLE
CellStyleBuilder.merge(Map[] sources) performance

### ISSUE THREAD

**Issue by jasonsaldo** [jameskleeh/groovy-excel-builder#23]
Merge escape statements always fail because sources.length is always 2. [null,null].length == 2.
This came up when profiling some larger sheet generation, [bx:10000]+. That sheet is causing GC overhead limit exceeded errors which I thought may be related to not using SXSSF, but maybe not.  

```
class CellStyleBuilder {
...
Map merge(Map[] sources) {
//These guards are always false and never executed
        if (sources.length == 0) {
            return [:]
        }
        if (sources.length == 1) {
            return sources[0]
        }
//this executes for ALL THE THINGS
        (Map)sources.inject([:]) { result, source ->
            source.each { k, v ->
                result[k] = result[k] instanceof Map ? merge((Map)result[k], (Map)v) : v
            }
            result
        }
    }
```

**Comment by jameskleeh** [comment]
> Merge escape statements always fail because sources.length is always 2

This is true but I doubt that is causing you any issues. If you track down any memory issues please file a new issue
