### ISSUE TITLE
Workbooks remain in memory when used in Grails App

### ISSUE THREAD

**Issue by leolion75** [jameskleeh/groovy-excel-builder#28]
When the plugin is used in a grails application, the workbooks that are exported remain in memory.  This is due to references on the closure passed to the build or output method of ExcelBuilder and the private static map,` CellStyleBuilder.WORKBOOK_CACHE`, that uses a workbook as the key.

I do not know the proper way to fix this otherwise I would submit a pull request, however as workaround, I was able to allow the Workbook to be garbage collected when I did the following:

```
def callable = { <builder DSL code> } 
def wb = ExcelBuilder.build callable
wb.write(out)
callable.delegate = null
CellStyleBuilder.WORKBOOK_CACHE.remove(wb)
wb.close()
```

Thanks,

Leo

**Comment by kortov** [comment]
It's reproducible for me. You don't even have to have a Grails App, I guess any console or spring app which uses ExcelBuilder.build will have this issue. Thanks for workaround, it helped!
