### ISSUE TITLE
RichTextFormat

### ISSUE THREAD

**Issue by vvanan** [jameskleeh/groovy-excel-builder#35]
I have to make a cell to accept rich text string. 
for eg if my string have <b>good</b>
then it has to display **good** in bold. 
Any solution for this please

**Comment by kortov** [comment]
How does the "good" string looks in code?

**Comment by Ashwinits** [comment]
> How does the "good" string looks in code?

<b>good</b>

**Comment by Ashwinits** [comment]
> How does the "good" string looks in code?

with html tag for bold

**Comment by Ashwinits** [comment]
> > How does the "good" string looks in code?
> 
> with html tag for bold
So along with applying html styling, need to set font name and size.

**Comment by jameskleeh** [comment]
I won't be implementing support for html tags in Excel. The breadth of that effort is much larger than I'm willing to take on.

**Comment by vvanan** [comment]
ok thanks. 
As of now we are able to use cell().setCellValue() for that purpose.

**Comment by jameskleeh** [comment]
@vvanan Are you saying that Excel supports HTML tags in cell values? The issue is just that we are assigning it via the string method?

**Comment by vvanan** [comment]
setCellValue(htmlToRichTextString.formatHtmlString(review.content, workbook))
written a method to preserve richtext format.

**Comment by kortov** [comment]
@vvanan FYI I guess this lib supports RTF https://github.com/dsl-builders/spreadsheet
