### ISSUE TITLE
Documentation for additional dependencies

### ISSUE THREAD

**Issue by eogiles** [jameskleeh/groovy-excel-builder#6]
Thanks for making this library available, I found it hugely helpful to getting an excel spreadsheet generated pretty quickly and elegantly and only had to dive into the POI api a couple times...

I did run into a couple dependency issues getting this set up in a Grails 2.5.x project (though I think they would probably be problems in any project) and thought I'd mention, in case you want to add these troubleshooting steps to your documentation. Or maybe there is a better way to solve these issues than I found:

Initially when trying to run a simple example I got the following class not found exception:
`org.openxmlformats.schemas.spreadsheetml.x2006.main.CTExtensionList`

I resolved this by adding a runtime dependency on the full POI schemas:
`runtime 'org.apache.poi:ooxml-schemas:1.3'`

However, that appeared to bring in its own dependency on an old version of xmlbeans (2.3.0), and I got the following exception next time I tried to run:
`NoSuchMethodError: org.apache.xmlbeans.XmlOptions.setLoadEntityBytesLimit(I)Lorg/apache/xmlbeans/XmlOptions;`

I resolved that by adding an explicit dependency to the more recent version of xmlbeans:
`runtime 'org.apache.xmlbeans:xmlbeans:2.6.0'`

Now everything works great! Hope this helps, thanks again.

**Comment by gudesh** [comment]
Same for me: very nice library, thanks, but...
I just spent hours chasing the same missing dependency, in order to get the doc's examples to run as Groovy scripts. (Too bad I didn't see this issue earlier)
Now it works and I can dig through the features !

**Comment by gudesh** [comment]
I also found a few typos in the documentation:
Font examples like `cell("A", [font: [name: "Arial"]`  sometimes miss a closing bracket.

**Comment by jameskleeh** [comment]
@gudesh I'll try to get to it, but feel free to submit a PR against the docs.
